<a href="https://colab.research.google.com/github/taufiqbal/gtmd/blob/main/model_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt

# Membaca data dari file CSV
file_path = '/content/drive/My Drive/Colab Notebooks/jpsi/fix_data_all.txt'
data = pd.read_csv(file_path)

# Memisahkan fitur input (Q^2, W, t) dan target output (sigma)
X = data[['Q^2', 'W', 't']].values
y = data['sigma'].values
error_bar = data['error_bar'].values

# Membagi data menjadi training dan testing set, termasuk error bar
X_train, X_test, y_train, y_test, error_bar_train, error_bar_test = train_test_split(
    X, y, error_bar, test_size=0.1, random_state=42
)

# Membangun model neural network
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(3,)))  # Layer input dengan 3 fitur
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))                                    # Layer dropout untuk regularization
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.5))                                    # Layer dropout untuk regularization
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='linear'))                   # Layer output untuk prediksi sigma

# Menggunakan MSE sebagai loss function
model.compile(optimizer=Adam(learning_rate=0.001), loss='mean_squared_error')

# Training model
history = model.fit(X_train, y_train, epochs=1000, batch_size=32, validation_split=0.2, verbose=1)

# Evaluasi model pada data testing
loss = model.evaluate(X_test, y_test)
print(f'Loss on test data: {loss}')

# Prediksi menggunakan model
predictions = model.predict(X_test)

# Menampilkan hasil prediksi bersamaan dengan data aktual
results_df = pd.DataFrame({
    'Q^2': X_test[:, 0],
    'W': X_test[:, 1],
    't': X_test[:, 2],
    'Actual Sigma': y_test,
    'Predicted Sigma': predictions.flatten(),
    'Error Bar': error_bar_test  # Menggunakan error bar dari set test yang benar
})

print(results_df)  # Menampilkan hasil prediksi dan data aktual

# Plotting training & validation loss
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 4s 144ms/step - loss: 32555.1855 - val_loss: 12223.2490
Epoch 2/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 29805.5254 - val_loss: 11933.8320
Epoch 3/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 27960.1641 - val_loss: 11504.5430
Epoch 4/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 29065.0039 - val_loss: 10887.8311
Epoch 5/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 23818.1914 - val_loss: 9950.0078
Epoch 6/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 21863.9238 - val_loss: 8621.9678
Epoch 7/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 21491.5312 - val_loss: 7141.6196
Epoch 8/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 24685.4570 - val_loss: 6192.0815
Epoch 9/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 20453.4863 - val_loss: 6015.9868
Epoch 10/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 18662.1816 - val_loss: 6010.7085
Epoch 11/1000
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 19981.8379 - v

In [ ]:
print(X)

[[5.00e-02 9.00e+01 3.00e-02]
 [5.00e-02 9.00e+01 1.00e-01]
 [5.00e-02 9.00e+01 1.70e-01]
 [5.00e-02 9.00e+01 2.50e-01]
 [5.00e-02 9.00e+01 3.50e-01]
 [5.00e-02 9.00e+01 4.90e-01]
 [5.00e-02 9.00e+01 7.30e-01]
 [5.00e-02 9.00e+01 1.03e+00]
 [3.20e+00 9.00e+01 4.00e-02]
 [3.20e+00 9.00e+01 1.30e-01]
 [3.20e+00 9.00e+01 2.70e-01]
 [3.20e+00 9.00e+01 6.80e-01]
 [7.50e+00 9.00e+01 4.00e-02]
 [7.50e+00 9.00e+01 1.30e-01]
 [7.50e+00 9.00e+01 2.70e-01]
 [7.50e+00 9.00e+01 6.80e-01]
 [2.24e+01 9.00e+01 4.00e-02]
 [2.24e+01 9.00e+01 1.30e-01]
 [2.24e+01 9.00e+01 2.70e-01]
 [2.24e+01 9.00e+01 6.80e-01]
 [3.10e+00 9.00e+01 5.00e-02]
 [3.10e+00 9.00e+01 1.50e-01]
 [3.10e+00 9.00e+01 2.90e-01]
 [3.10e+00 9.00e+01 5.80e-01]
 [6.80e+00 9.00e+01 5.00e-02]
 [6.80e+00 9.00e+01 1.50e-01]
 [6.80e+00 9.00e+01 2.90e-01]
 [6.80e+00 9.00e+01 5.80e-01]
 [6.80e+00 9.00e+01 5.00e-02]
 [6.80e+00 9.00e+01 1.50e-01]
 [6.80e+00 9.00e+01 2.90e-01]
 [6.80e+00 9.00e+01 5.80e-01]
 [1.60e+01 9.00e+01 5.00e-02]
 [1.60e+01

In [ ]:
print(y)

[285.   180.   130.    92.1   61.2   32.5   10.6    2.7  107.    95.1
  40.2    8.04  78.6   27.7   18.9    5.21  15.     8.9    4.55   1.36
 148.    86.9   49.2   10.7   79.2   43.9   25.8    6.    75.6   39.6
  23.9    6.5   28.    15.6    9.4    1.8  182.   208.   225.   321.
 292.   326.   392.   376.   458.   537.   744.   115.   118.   169.
 151.   178.   224.   226.   265.   267.   427.   573.    64.9   69.6
 107.1   93.4  132.   135.   125.   142.   167.   202.   246.    35.5
  35.6   34.3   38.9   41.4   46.3   48.5   60.9   51.5   67.    71.6
   5.7    5.5    6.2    7.1    8.2    7.5    7.7    8.2    8.4   10.7
  13.1   33.3   51.3   60.    17.3   30.1   31.5    3.4    5.5    6.  ]


In [ ]:
print(X_test)

[[5.00e-02 7.50e+01 8.30e-01]
 [5.00e-02 1.05e+02 1.00e-01]
 [5.00e-02 5.50e+01 4.30e-01]
 [5.00e-02 1.81e+02 3.00e-02]
 [5.00e-02 1.44e+02 3.00e-02]
 [5.00e-02 7.50e+01 3.00e-02]
 [3.10e+00 9.00e+01 2.90e-01]
 [5.00e-02 4.50e+01 8.30e-01]
 [3.20e+00 9.00e+01 2.70e-01]
 [5.00e-02 9.00e+01 3.00e-02]]


In [ ]:
print(y_test)

[  7.1 226.   35.6 537.  458.  321.   49.2   5.7  40.2 285. ]


In [ ]:
print(data)

     Q^2      W     t  sigma  error_bar
0   0.05   90.0  0.03  285.0      26.57
1   0.05   90.0  0.10  180.0      17.46
2   0.05   90.0  0.17  130.0      12.53
3   0.05   90.0  0.25   92.1       9.03
4   0.05   90.0  0.35   61.2       6.23
..   ...    ...   ...    ...        ...
95  8.90   98.0  0.19   30.1       4.55
96  8.90  140.0  0.19   31.5       6.53
97  8.90   57.0  0.64    3.4       0.58
98  8.90   98.0  0.64    5.5       0.86
99  8.90  140.0  0.64    6.0       1.25

[100 rows x 5 columns]
